imports:
    - path: ../templates/project.py
      name: project.py

resources:
    - name: project
      type: project.py
      properties:
        parent_node: 
            type: organization
            id: 279306703376
        billing_account_id: 010FAB-0BB731-1EBA39