imports:
    - path: ../templates/app.py
      name: app.py
    - path: ../templates/folders.py
      name: folders.py

resources:
    - name: ww-app-four
      type: folders.py
      properties:
        parent_node: 
            type: organization
            id: 279306703376

    - name: ww-app-five
      type: folders.py
      properties:
        parent_node:
          type: organization
          id: 279306703376

    - name: ww-app-six
      type: folders.py
      properties:
        parent_node:
          type: organization
          id: 279306703376