imports:
    - path: ../templates/app.py
      name: app.py

resources:
    - name: ww-application-five
      type: app.py
      properties:
        owners:
        - sketchbang@gmail.com
        root_node: 1029401591345
        dev_node: 761404088872
        prd_node: 467841586597
        billing_account_id: 010FAB-0BB731-1EBA39
        
        enabled_services:
          - compute.googleapis.com
          - pubsub.googleapis.com

